apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app.yaml
  - simulation.yaml
  - geo-rs.yaml
  - ai.yaml
  - redis.yaml
  - opensearch.yaml
  - temporal.yaml
  - permify.yaml
  - configmap.yaml
  - secrets-template.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: policy-twin
